var pipu_examples = [
    ["The sun shines.", "sun sun-verb"],
    ["The sun is shining.", "sun sun-verb now"],
    ["The sun shone.", "sun sun-past"],
    ["The sun will shine.", "sun sun-will"],
    ["The sun has been shining.", "sun sun-past"],
    ["The sun is shining again.", "sun sun-verb new"],
    ["The sun will shine tomorrow.", "sun sun-will tomorrow"],
    ["The sun shines brightly.", "sun sun-verb fire-adj"],
    ["The bright sun shines.", "fire-adj sun sun-verb"],
    ["The sun is rising now.", "sun up-verb now"],
    ["All the people shouted.", "person all noise-past"],
    ["Some of the people shouted.", "person partial-adj noise-past"],
    ["Many of the people shouted twice.", "person all-adj noise-past 002"],
    ["Happy people often shout.", "person positive-adj noise-verb sometimes"],
    ["The kitten jumped up.", "animal up-past"],
    ["The kitten jumped onto the table.", "animal up-past table"],
    ["My little kitten walked away.", "me now-adj animal there-verb"],
    ["It's raining.", "rain-verb"],
    ["The rain came down.", "rain down-past"],
    ["The kitten is playing in the rain.", "animal happiness-verb within rain"],
    ["The rain has stopped.", "rain stop-verb"],
    ["Soon the rain will stop.", "rain stop-verb time-adj"],
    ["I hope the rain stops soon.", "I desire-verb rain stop-verb time-adj"],
    ["Once wild animals lived here.", "animal life-adj life-past here"],
    ["Slowly she looked around.", "she eye-verb slow-adj here-adj"],
    ["Go away!", "you there-verb"],
    ["Let's go!", "we_inclusive there-verb"],
    ["You should go.", "you there-verb if_then-adj"],
    ["I will be happy to go.", "I-will happiness-adj there-verb"],
    ["He will arrive soon.", "he here-will time-adj"],
    ["The baby's ball has rolled away.", "child circle-of there-past"],
    ["The two boys are working together.", "child 002 work-verb unison-adj"],
    ["This mist will probably clear away.", "this rain light-adj there-verb ease-adj"],
    ["Lovely flowers are growing everywhere.", "plant happiness-adj plant-verb everywhere"],
    ["We should eat more slowly.", "we_inclusive mouth-verb start-adj if_then-adj"],
    ["You have come too soon.", "you here-verb time-adj tall-adj"],
    ["You must write more neatly.", "you hand-verb good-adj adult-adj compare_to-adj"],
    ["Directly opposite stands a wonderful palace.", "opposite here-verb building happiness-adj"],
    ["Henry's dog is lost.", "wew-prop animal unknown_location-adj"],
    ["My cat is black.", "me animal 000"],
    ["The little girl's doll is broken.", "child female toy-of destroy-adj"],
    ["I usually sleep soundly.", "me night normality-of normality-adj"],
    ["The children ran after Jack.", "child leg-past speed-adj cak-prop unison-adj"],
    ["I can play after school.", "I toy-will positive-adj afterwards education"],
    ["We went to the village for a visit.", "we_exclusive here-past village for visit"],
    ["We arrived at the river.", "we_exclusive here-past river"],
    ["I have been waiting for you.", "I later-past for you"],
    ["The campers sat around the fire.", "person nature calm-verb here-adj fire"],
    ["A little girl with a kitten sat near me.", "child female and animal calm-verb here-adj me"],
    ["The child waited at the door for her father.", "child door later-past for adult actor"],
    ["Yesterday the oldest girl in the village lost her kitten.", "child female village old-adj yesterday-adj unknown_location-past animal actor yesterday"],
    ["Were you born in this village?", "you birth-past question within this village"],
    ["Can your brother dance well?", "you family male happiness-verb good-adj question"],
    ["Did the man leave?", "male there-past question"],
    ["Is your sister coming for you?", "you family female here-will for you"],
    ["Can you come tomorrow?", "you here-will positive-adj tomorrow"],
    ["Have the neighbors gone away for the winter?", "neighbour there-past question for Winter"],
    ["Does the robin sing in the rain?", "animal music-verb question within rain"],
    ["Are you going with us to the concert?", ""],
    ["Have you ever travelled in the jungle?", ""],
    ["We sailed down the river for several miles.", ""],
    ["Everybody knows about hunting.", ""],
    ["On a Sunny morning after the solstice we started for the mountains.", ""],
    ["Tom laughed at the monkey's tricks.", ""],
    ["An old man with a walking stick stood beside the fence.", ""],
    ["The squirrel's nest was hidden by drooping boughs.", ""],
    ["The little seeds waited patiently under the snow for the warm spring sun.", ""],
    ["Many little girls with wreaths of flowers on their heads danced around the bonfire.", ""],
    ["The cover of the basket fell to the floor.", ""],
    ["The first boy in the line stopped at the entrance.", ""],
    ["On the top of the hill in a little hut lived a wise old woman.", ""],
    ["During our residence in the country we often walked in the pastures.", ""],
    ["When will your guests from the city arrive?", ""],
    ["Near the mouth of the river, its course turns sharply towards the East.", ""],
    ["Between the two lofty mountains lay a fertile valley.", ""],
    ["Among the wheat grew tall red poppies.", ""],
    ["The strong roots of the oak trees were torn from the ground.", ""],
    ["The sun looked down through the branches upon the children at play.", ""],
    ["The west wind blew across my face like a friendly caress.", ""],
    ["The spool of thread rolled across the floor.", ""],
    ["A box of growing plants stood in the Window.", ""],
    ["I am very happy.", ""],
    ["These oranges are juicy.", ""],
    ["Sea water is salty.", ""],
    ["The streets are full of people.", ""],
    ["Sugar tastes sweet.", ""],
    ["The fire feels hot.", ""],
    ["The little girl seemed lonely.", ""],
    ["The little boy's father had once been a sailor.", ""],
    ["I have lost my blanket.", ""],
    ["A robin has built his nest in the apple tree.", ""],
    ["At noon we ate our lunch by the roadside.", ""],
    ["Mr. Jones made a knife for his little boy.", ""],
    ["Their voices sound very happy.", ""],
    ["Is today Monday?", ""],
    ["Have all the leaves fallen from the tree?", ""],
    ["Will you be ready on time?", ""],
    ["Will you send this message for me?", ""],
    ["Are you waiting for me?", ""],
    ["Is this the first kitten of the litter?", ""],
    ["Are these shoes too big for you?", ""],
    ["How wide is the River?", ""],
    ["Listen.", ""],
    ["Sit here by me.", ""],
    ["Keep this secret until tomorrow.", ""],
    ["Come with us.", ""],
    ["Bring your friends with you.", ""],
    ["Be careful.", ""],
    ["Have some tea.", ""],
    ["Pip and his dog were great friends.", ""],
    ["John and Elizabeth are brother and sister.", ""],
    ["You and I will go together.", ""],
    ["They opened all the doors and windows.", ""],
    ["He is small, but strong.", ""],
    ["Is this tree an oak or a maple?", ""],
    ["Does the sky look blue or gray?", ""],
    ["Come with your father or mother.", ""],
    ["I am tired, but very happy.", ""],
    ["He played a tune on his wonderful flute.", ""],
    ["Toward the end of August the days grow much shorter.", ""],
    ["A company of soldiers marched over the hill and across the meadow.", ""],
    ["The first part of the story is very interesting.", ""],
    ["The crow dropped some pebbles into the pitcher and raised the water to the brim.", ""],
    ["The baby clapped her hands and laughed in glee.", ""],
    ["Stop your game and be quiet.", ""],
    ["The sound of the drums grew louder and louder.", ""],
    ["Do you like summer or winter better?", ""],
    ["That boy will have a wonderful trip.", ""],
    ["They popped corn, and then sat around the fire and ate it.", ""],
    ["They won the first two games, but lost the last one.", ""],
    ["Take this note, carry it to your mother; and wait for an answer.", ""],
    ["I awoke early, dressed hastily, and went down to breakfast.", ""],
    ["Aha! I have caught you!", ""],
    ["This string is too short!", ""],
    ["Oh, dear! the wind has blown my hat away!", ""],
    ["Alas! that news is sad indeed!", ""],
    ["Whew! that cold wind freezes my nose!", ""],
    ["Are you warm enough now?", ""],
    ["They heard the warning too late.", ""],
    ["We are a brave people, and love our country.", ""],
    ["All the children came except Mary.", ""],
    ["Jack seized a handful of pebbles and threw them into the lake.", ""],
    ["This cottage stood on a low hill, at some distance from the village.", ""],
    ["On a fine summer evening, the two old people were sitting outside the door of their cottage.", ""],
    ["Our bird's name is Jacko.", ""],
    ["The river knows the way to the sea.", ""],
    ["The boat sails away, like a bird on the wing.", ""],
    ["They looked cautiously about, but saw nothing.", ""],
    ["The little house had three rooms, a sitting room, a bedroom, and a tiny kitchen.", ""],
    ["We visited my uncle's village, the largest village in the world.", ""],
    ["We learn something new each day.", ""],
    ["The market begins five minutes earlier this week.", ""],
    ["Did you find the distance too great?", ""],
    ["Hurry, children.", ""],
    ["Madam, I will obey your command.", ""],
    ["Here under this tree they gave their guests a splendid feast.", ""],
    ["In winter I get up at night, and dress by yellow candlelight.", ""],
    ["Tell the last part of that story again.", ""],
    ["Be quick or you will be too late.", ""],
    ["Will you go with us or wait here?", ""],
    ["She was always, shabby, often ragged, and on cold days very uncomfortable.", ""],
    ["Think first and then act.", ""],
    ["I stood, a little mite of a girl, upon a chair by the window, and watched the falling snowflakes.", ""],
    ["Show the guests these shells, my son, and tell them their strange history.", ""],
    ["Be satisfied with nothing but your best.", ""],
    ["We consider them our faithful friends.", ""],
    ["We will make this place our home.", ""],
    ["The squirrels make their nests warm and snug with soft moss and leaves.", ""],
    ["The little girl made the doll's dress herself.", ""],
    ["I hurt myself.", ""],
    ["She was talking to herself.", ""],
    ["He proved himself trustworthy.", ""],
    ["We could see ourselves in the water.", ""],
    ["Do it yourself.", ""],
    ["I feel ashamed of myself.", ""],
    ["Sit here by yourself.", ""],
    ["The dress of the little princess was embroidered with roses, the national flower of the Country.", ""],
    ["They wore red caps, the symbol of liberty.", ""],
    ["With him as our protector, we fear no danger.", ""],
    ["All her finery, lace, ribbons, and feathers, was packed away in a trunk.", ""],
    ["Light he thought her, like a feather.", ""],
    ["Every spring and fall our cousins pay us a long visit.", ""],
    ["In our climate the grass remains green all winter.", ""],
    ["The boy who brought the book has gone.", ""],
    ["These are the flowers that you ordered.", ""],
    ["I have lost the book that you gave me.", ""],
    ["The fisherman who owned the boat now demanded payment.", ""],
    ["Come when you are called.", ""],
    ["I shall stay at home if it rains.", ""],
    ["When he saw me, he stopped.", ""],
    ["Do not laugh at me because I seem so absent minded.", ""],
    ["I shall lend you the books that you need.", ""],
    ["Come early next Monday if you can.", ""],
    ["If you come early, wait in the hall.", ""],
    ["I had a younger brother whose name was Antonio.", ""],
    ["Gnomes are little men who live under the ground.", ""],
    ["He is loved by everybody, because he has a gentle disposition.", ""],
    ["Hold the horse while I run and get my cap.", ""],
    ["I have found the ring I lost.", ""],
    ["Play and I will sing.", ""],
    ["That is the funniest story I ever heard.", ""],
    ["She is taller than her brother.", ""],
    ["They are no wiser than we.", ""],
    ["Light travels faster than sound.", ""],
    ["We have more time than they.", ""],
    ["She has more friends than enemies.", ""],
    ["He was very poor, and with his wife and five children lived in a little low cabin of logs and stones.", ""],
    ["When the wind blew, the traveler wrapped his mantle more closely around him.", ""],
    ["I am sure that we can go.", ""],
    ["We went back to the place where we saw the roses.", ""],
    ["\"This tree is fifty feet high,\" said the gardener.", ""],
    ["I think that this train leaves five minutes earlier today.", ""],
    ["My opinion is that the governor will grant him a pardon.", ""],
    ["Why he has left the city is a mystery.", ""],
    ["The house stands where three roads meet.", ""],
    ["He has far more money than brains.", ""],
    ["Evidently that gate is never opened, for the long grass and the great hemlocks grow close against it.", ""],
    ["I met a little cottage girl; she was eight years old, she said.", ""]
];
